backend/controllers/auth.js, backend/controllers/index.js, backend/middlewares/auth0api.js, backend/package-lock.json, backend/package.json
=> Added authorization middleware for api and login/logout endpoints with Auth0

backend/controllers/queue.js, backend/index.js, backend/lib/db/connections.js, backend/lib/db/mongodb.js, backend/lib/log.js, backend/lib/models/queue.js, backend/lib/models/user.js, backend/package-lock.json, backend/package.json
- Implemented MongoDB
- Used `winston` for logging
- `/api/queue` endpoints are set up
- missing endpoint protection, but that will be setup down the line
- `.env` usage
=> DB, Logger, Basic Queue Endpoints

meetings/feb-5-2022.md
=> February 5th meeting notes

backend/controllers/queue.js
Issue "Pop User from Queue Endpoint https://github.com/jchen42703/waiting-line-app/issues/5"
=> pop first user in queue

packages/backend/src/controllers/index.ts, packages/backend/src/controllers/queue.ts, packages/shared-dto/index.ts, packages/shared-dto/queue.ts, packages/shared-dto/src/User.ts
This change converts the code in queue to typescript.   queue.js --> queue.ts
Same as queue.js 
N/A
=> Convert Queue to typescript

packages/backend/package.json, packages/backend/src/controllers/queue.ts, packages/backend/src/index.ts, packages/backend/src/lib/errors.ts, packages/backend/src/lib/log.ts, packages/backend/src/lib/parse.ts, packages/backend/src/middleware/error.ts, packages/shared-dto/errors.ts, yarn.lock
Error Middleware + Better Logging + Added validation to queue routes
These don't exist and invalid input params for queue routes work, which shouldn't happen.
Handling operational errors should be done by:
`return next(new HttpException(statusCode, errMessage)`
The queue routes now have a lot cleaner input parameter validation (i.e. type checking, db checks are `try/catch`'d
=> Error Middleware + Better Logging + Added validation to queue routes

packages/backend/src/controllers/queue.ts, packages/backend/src/lib/models/queue/queue.service.ts, packages/shared-dto/queue.ts
Created an endpoint for /api/queue/all
returns a list of users
- 
=> Created endpoint for api/queue/all

packages/ui/src/components/AdminNavBar.tsx, packages/ui/src/components/dashboard/landingPage/LandingPageTableRow.tsx, packages/ui/src/components/dashboard/landingPage/StatusCircle.tsx, packages/ui/src/views/App.tsx, packages/ui/src/views/dashboard/dashboard.tsx, packages/ui/src/views/settings/settings.tsx
=> Theming + /dashboard cleaner component

packages/backend/src/controllers/queue.ts, packages/shared-dto/queue.ts, packages/shared-dto/src/queue.ts
=> Delete User Endpoint

packages/ui/src/components/AdminNavBar.tsx, packages/ui/src/components/Drawer.tsx, packages/ui/src/components/dashboard/landingPage/AllQueuesTable.tsx, packages/ui/src/components/dashboard/landingPage/LandingPageTableRow.tsx, packages/ui/src/components/dashboard/landingPage/StatusCircle.tsx, packages/ui/src/components/tables/CenteredTableCell.tsx, packages/ui/src/views/App.tsx, packages/ui/src/views/dashboard/dashboard.tsx
Table in `Dashboard` has now been moved to `AllQueuesTable`. `AllQueuesTable` has been styled better (hover, clearer text, table outline) and has routing functionality.
=> Slight Improvements to `Dashboard`

packages/ui/package.json, packages/ui/src/components/dashboard/analytics/QR.tsx, packages/ui/src/lib/config.ts, packages/ui/src/views/dashboard/analyticsDashboard.tsx, packages/ui/src/views/users/UserSignupPage.tsx, tsconfig.json
Added `QR.tsx` which creates QR code so users can scan to join the specific `queueId`. 
Added `frontendUrl` to `config.ts`.
=> Added QRCode generator

packages/ui/src/components/UserWaitingStatus.tsx, packages/ui/src/views/users/UserSignupPage.tsx, packages/ui/src/views/users/UserWaitingPage.tsx
=> Fixed the bug that "could not find queue" error wasn't detected when joining.

packages/backend/src/controllers/queue.ts, packages/backend/src/lib/models/queue/queue.service.ts, packages/shared-dto/src/queue.ts
=> [backend] delete queue endpoint

packages/backend/src/controllers/queue.ts, packages/backend/src/lib/models/queue/queue.service.ts, packages/shared-dto/src/queue.ts
POST `/api/queue/metadata` to update queue metadata
=> Edit Queue Metadata Endpoint

packages/backend/src/controllers/admin.ts, packages/shared-dto/src/admin.ts
=> [backend] get single queue endpoint

packages/ui/src/components/dashboard/landingPage/AllQueuesTable.tsx, packages/ui/src/components/dashboard/landingPage/DeleteQueueModal.tsx, packages/ui/src/components/dashboard/landingPage/LandingPageTableRow.tsx, packages/ui/src/components/dashboard/landingPage/QueueTableManager.tsx, packages/ui/src/components/dashboard/landingPage/StatusCircle.tsx, packages/ui/src/lib/services/queue.service.ts
=> Delete Queue in Landing Admin Dashboard (`/dashboard`)

packages/backend/src/controllers/admin.ts, packages/backend/src/controllers/auth.ts, packages/shared-dto/src/admin.ts, packages/ui/src/components/AdminNavBar.tsx, packages/ui/src/components/Drawer.tsx, packages/ui/src/lib/services/admin.service.ts, packages/ui/src/lib/services/auth.service.ts
=> Can now logout and navigate queues through `AdminNavbar`

packages/ui/src/components/dashboard/analytics/widgets/QueueListWidget.tsx
=> Add link to QueueList widget

packages/backend/src/controllers/admin.ts, packages/backend/src/controllers/queue.ts, packages/backend/src/lib/models/queue/queue.model.ts, packages/backend/src/lib/models/queue/queue.service.ts, packages/backend/src/lib/models/user.ts, packages/shared-dto/src/admin.ts, packages/shared-dto/src/db.ts, packages/shared-dto/src/queue.ts, packages/ui/src/components/UserWaitingStatus.tsx, packages/ui/src/components/dashboard/userManager/UserInfoRow.tsx, packages/ui/src/components/dashboard/userManager/UserTable.tsx, packages/ui/src/components/dashboard/userManager/UserTableManager.tsx, packages/ui/src/lib/services/user.service.ts
=> Notify User Works

packages/ui/src/components/dashboard/analytics/Layout.tsx, packages/ui/src/components/dashboard/analytics/widgets/BanWidget.tsx
=> Add banned list and fetch call
